server:
  port: 8080

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/savemsg
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true

